tasks:
- init: pip install -r requirements.txt
  command: mkdocs serve --dev-addr localhost:8888
ports:
- port: 8888
  onOpen: open-preview
gitConfig:
  user.name: Shao Wang
  user.email: shao.wang.me@gmail.com
